# Generated by Django 3.0.4 on 2020-04-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BYARENT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
