# Generated by Django 3.0.4 on 2020-04-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BYARENT', '0003_auto_20200412_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='publication_date',
        ),
    ]
