# Generated by Django 3.0.4 on 2020-04-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BYARENT', '0004_remove_home_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='home',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
