# Generated by Django 3.0.4 on 2020-04-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BYARENT', '0005_auto_20200424_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='rent',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='sale',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
